### ISSUE TITLE
Support for nested classes

### ISSUE THREAD

**Issue by dustincatap** [smotastic/smartstruct#10]
Is it possible to map classes with subclasses?

```dart
// Input

class MyClass {
  MyClass(this.mySubClass);

  final MySubClass mySubClass;
}

class MySubClass {
  MySubClass(this.myProperty);

  final String myProperty;
}

// Output

class MyClassModel {
  MyClassModel(this.mySubClass);

  final MySubClassModel mySubClass;
}

class MySubClassModel {
  MySubClassModel(this.myProperty);

  final String myProperty;
}
```

**Comment by smotastic** [comment]
Right now it would just try to map the subclassmodel to subclass, which would result in an error.

```dart
  MyClass fromModel(MyClassModel model) {
    final myclass = MyClass(model.mySubClass);
    return myclass;
  }
```

I´m thinking of doing something similar to mapstruct, where you can define a mapper method for the subclass in the same mapper interface, and the mapper method for the class, will then be able to use the subclass method. 
```dart
// mapper.dart
@Mapper()
abstract class SubClassMapper {
  MyClass fromModel(MyClassModel model);

  MySubClass fromSubClassModel(MySubClassModel model);
}
```
Which would result in something like this.
```dart
// mapper.g.dart
class SubClassMapperImpl extends SubClassMapper {
  @override
  MyClass fromModel(MyClassModel model) {
    final myclass = MyClass(fromSubClassModel(model.mySubClass));
    return myclass;
  }

  @override
  MySubClass fromSubClassModel(MySubClassModel model) {
    final mysubclass = MySubClass(model.myProperty);
    return mysubclass;
  }
}
```
https://mapstruct.org/documentation/stable/reference/html/index.html#basic-mappings

I´ll see if I find some time on the weekend, or if you already have an idea, feel free to create a pull request.

**Comment by smotastic** [comment]
I added support for nested bean mapping. See #10
Here is an example https://github.com/smotastic/smartstruct/tree/master/example/lib/nested
And the published package https://pub.dev/packages/smartstruct
I'm still missing some tests, which will be added in #8
