### ISSUE TITLE
Improvement custom field

### ISSUE THREAD

**Issue by Rodrigolmti** [smotastic/smartstruct#26]
Hi, this is a great package thanks for sharing. I did look at the documentation and did not see anything like...

For example, I have the class 

`
class UserResponse {
final String profile;
...
}
`

And I have

```
enum UserProfile { investor, consumer }

class User {
final UserProfile profile;
...
}
```

How can I make the mapper to map with a custom logic for example:

```
profile: enumFromString<UserProfile>(
    UserProfile.values,
    response.profile,
    UserProfile.consumer,
  )
```

for the profile field. This is just one example there is several more like 

```
class UserResponse {
   final String zipCode;
   final String number;
   final String street;
...
}
```

Map to 

```
class User {
   final Address address;
}
```

**Comment by smotastic** [comment]
Hi @Rodrigolmti 
I like the idea, I was thinking of something like 
```dart
@Mapper()
class UserResponseMapper{
    @Mapping(source: 'zipCode', target: 'response.address.zipCode')
    User fromUserResponse(UserResponse response);
}
```
The mapper could automatically determine the address field in the Target User Object, and map the fields according to the configuration. See also https://mapstruct.org/documentation/dev/reference/html/#mappings-with-several-source-parameters

Right now as a workaround, you could try providing multiple mapper methods, so the desired mapper method can automatically map the nested bean.
```dart
@Mapper()
class UserMapper {
  User fromUserResponse(UserResponse response);
  Address fromUserResponseAddress(UserResponse response);
}
```
The fromUserResponse would now automatically call the fromUserResponseAddress to map its Address. See also https://github.com/smotastic/smartstruct/blob/master/example/lib/nested/nested.dart

I'll see what I can do, or if you feel like it, feel free to open a PR

**Comment by smotastic** [comment]
Hi, I just merged this feature.

Now you can write something like this
```dart
@Mapper()
abstract class UserMapper {
  @Mapping(target: 'zipcode', source: 'response.address.zipcode')
  @Mapping(target: 'street', source: 'response.address.street.streetName')
  User fromResponse(UserResponse response);
}
```
To directly map nested models in the mapper.

See also the examples (https://github.com/smotastic/smartstruct/blob/develop/example/lib/nested/nested_mapping.dart)
