### ISSUE TITLE
Support inheritance

### ISSUE THREAD

**Issue by dustincatap** [smotastic/smartstruct#30]
Will it be possible to map objects that inherit other objects?

i.e.

```dart
class BaseClass {
  BaseClass({required this.id});

  final String id;
}

class MyClass extends BaseClass {
  MyClass({required this.name, required String id}) : super(id: id);

  final String name;
}
```

**Comment by smotastic** [comment]
Hey, that's a good point. Currently, I'm only reading the fields of the current class, but of course, it would make sense to also read all the fields from the super classes.
Should be a relatively easy fix, I'll see if I find some time
