### ISSUE TITLE
@ignore annotation to exclude field from mapper 

### ISSUE THREAD

**Issue by luissalgadofreire** [smotastic/smartstruct#40]
Thanks for the library. I'm a fan of Mapstruct and it's good to see a similar effort in the dart world.

One question or feature request. Is it possible to exclude a field from the automatic mapper, something similar to [this](https://stackoverflow.com/questions/55179700/flag-to-ignore-serialization-of-property-build-runner)?

The less we explicitly name the fields, the easier it becomes to maintain the mappings. This is particularly relevant when using  libraries like Equatable that add helper fields we do not want to include in our mappings.

This would allow scenarios where we could say "map all fields except this one" as opposed to having to explicitly map all the ones we want.

**Comment by smotastic** [comment]
Hey, sorry for the late response.
I like the idea, and this is definitely something I'd like to see in this library.
I'll see if I find some time in the coming days, or if you feel like it, feel free to open a PR

**Comment by smotastic** [comment]
Hi @luissalgadofreire 
I pushed a fix for this issue.
Now you can ignore certain fields with help of the @Mapping annotation.

```dart
@Mapper()
abstract class DogMapper {
  @Mapping(target: 'id', ignore: true)
  DogTarget fromIgnore(DogSource source);
}
```
Will ignore the mapping for the id property.

This will not fix the issue of having to explicitly name all the fields in your mapping annotation though.
In your example the ignore Annotation would directly sit at the field at the Entity Level. 
This solution orients itself more at the solution mapstruct provides, directly in the mapper.
( see https://mapstruct.org/documentation/stable/reference/html/#mapping-composition )
My reasoning to follow this approach is to decouple mapper logic from business entities / models.
I like having all the configuration for the mapper in the mapper itself, so the model / entity can still be used independently from smartstruct.
As a drawback of course, you have to explicitly name all the fields in the mapper, not the entity, you want to ignore.

I hope this will help you. If you think the annotation would be better on Entity Level, feel free to open another issue, i'm always open to discussion

(Release will come sometime today)
