### ISSUE TITLE
Static Function Mapping for map Enums, List, Maps, Set not working

### ISSUE THREAD

**Issue by smotastic** [smotastic/smartstruct#68]
@smotastic  Hi, thanks for info. 

I've tested new commits and unfortunately there is still broken Static mapping. 

With this new change, it is not possible add helper methods for map Enums, List, Maps, Set or anything that is not a class as it generates invalid code 
```
static EnumFoo _mapEnumFoo(Source model) => model.foo ... 
static List<String> _mapNames(Source model) => model.friends.map((f) => f.name).toList()
```
both will generate something like

```
EnumFoo _$_mapEnumFoo(Source model) {
   final enumFoo = EnumFoo._();
   return enumFoo;
}
```
for List it wil generate similar code. 

**So for now** within my fork I've completely reverted static mapping as it is not usable in my application.

_Originally posted by @petrnymsa in https://github.com/smotastic/smartstruct/issues/58#issuecomment-1214401368_

**Comment by luissalgadofreire** [comment]
Sorry. Just noticed the note in the pull request to use `@IgnoreMapping`.

**Comment by smotastic** [comment]
Correct. In this pull #73 I also added Enum as a default to be ignored by static mapping.
So currently you will need the annotation, in 1.3.1 it will be ignored by default.

**Comment by luissalgadofreire** [comment]
Thanks, it's clear now.

I can confirm it's all working now, once I added the annotation to all my Enum mappings.
