### ISSUE TITLE
Is support for mapping class with generic type?

### ISSUE THREAD

**Issue by putrautama007** [smotastic/smartstruct#85]
Hello,
I want to ask is smartstruct support to mapping class with generic type?
Thank you

**Comment by namlxcntt** [comment]
I have using freezed and json 

Same class 

`
@Freezed(genericArgumentFactories: true)
class ResponseWrapper<T> with _$ResponseWrapper<T>{
  const factory ResponseWrapper ({
    final int? status,
    final T? data,
    final String? message
  }) = _ResponseWrapper;

  factory ResponseWrapper.fromJson(Map<String, dynamic> json,
      T Function(Object? json) fromJsonT)
  => _$ResponseWrapperFromJson<T>(json, fromJsonT);
}`

**Comment by putrautama007** [comment]
> I have using freezed and json
> 
> Same class
> 
> ` @freezed(genericArgumentFactories: true) class ResponseWrapper with _$ResponseWrapper{ const factory ResponseWrapper ({ final int? status, final T? data, final String? message }) = _ResponseWrapper;
> 
> factory ResponseWrapper.fromJson(Map<String, dynamic> json, T Function(Object? json) fromJsonT) => _$ResponseWrapperFromJson(json, fromJsonT); }`

okay thank you for help
